### ISSUE TITLE
Details page does not show all content, if too long

### ISSUE THREAD

**Issue by ctel** [RocketChat/Rocket.Chat.Cordova#210]
This issue is a copy of the [issue #482 here](https://github.com/RocketChat/Rocket.Chat.Android/issues/482)

My Rocket.Chat.Android version: 2.5.0
Mobile device model and OS version: Huawei Honor 8 - Android 7.0, EMUI 5.0
Resolution (might be related to this bug, so I spare you the lookup ;)): 1080 x 1920

It is a visual bug: Just open the details page of a group or user, as seen on the screenshot.
Not all buttons should be visible (partial visibility) and the scrollbar is at its lowest possible position.

Left: screenshot from mobile device; visible area ends abruptly on the bottom
Right: desktop screenshot as it should be; just for reference
![screenshots](https://user-images.githubusercontent.com/9321348/30976345-da8bc298-a474-11e7-9ae3-48351b51d78f.png)

**Comment by ccfang** [comment]
@ctel Hi, try using admin and go to Administration → Layout → Custom CSS, add below css code to fix this problem temporarily.

```css
@media all and (max-width: 780px) {
  .flex-tab-container .flex-tab .content > .animated {
    height: 90%;
  }
}
```
